### ISSUE TITLE
Should file-scoped namespace declarations be used?

### ISSUE THREAD

**Issue by thailyn** [emipa606/PawnsChooseResearch#5]
This is more of a question than a bug or issue, really. I used to program professionally in C#, but it's been about 10 years and I'm not that familiar with newer language versions features.

I noticed the source code files in this repo are using [file-scoped namespaces declarations](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces), but this appears to be a feature introduced in [C# 10.0](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration).

However, this project's `csproj` file sets the target framework to be .NET Framework 4.8:
https://github.com/emipa606/PawnsChooseResearch/blob/2e5d49c389ea6215b02a11ab3c4e5b94ef41ecea/Source/PawnsChooseResearch/PawnsChooseResearch.csproj#L4

When I downloaded the repo and tried to compile it, I was getting [CS1514](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1514) errors. To be fair, I am using version 16.11.19 of Visual Studio Community 2019, and I don't have any later version of the .NET Framework, .NET Core, or .NET installed (I haven't had a need). However, every reference I've seen (e.g., the [RimWorld wiki](https://rimworldwiki.com/wiki/Modding_Tutorials/Setting_up_a_solution#Option_1_.28Manual_Method.29:)) indicate to target an "old" version of the .NET Framework, such as 4.7.2. I think RimWorld 1.4 might have pushed that forward a bit, but I don't think all the way to [C# 10.0 / .NET 6.0](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)#Versions).

So, after all that, my question is whether file-scoped namespace declarations should be used in RimWorld mods. If one has a newer version of Visual Studio, it might compile fine and just be converted to the old format when targeting a pre-C# 10.0 version of the language (when I decompiled the assembly I downloaded from Steam it showed the old style of namespace declarations), but it might then cause issues for anyone who is configured for the [minimum] requirements for RimWorld modding.

**Comment by emipa606** [comment]
I am aware that many still uses the old c# syntax for this and a lot of other things, but since I am used to using the latest version and stay on top of new language features in my current employment its not really feasible for me to jump back to an older version just for modding.
If there should appear any incompatibilities due to this I could downgrade it for that particular mod of course but I have yet so see anything like that in the 570~ mods with assemblies that I've currently updated using this format.
I have it on my list to write a guide for setting up VS but have yet to find the time for it.
